import "slick-carousel/slick/slick.css";
import "slick-carousel/slick/slick-theme.css";
import "./globals.css";
import type { Metadata } from "next";
import { Inter } from "next/font/google";
import { title } from "process";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <div className="max-w-3xl">{children}</div>
      </body>
    </html>
  );
}

/*
home
- cityMovieSection
  - *cityList* 
  - *movieScrollList-small*
- countryMovieSection
  - *countryList*
  - *movieScrollList-small*
- KeywordMovieSection
  - *keywordList*


movies/cities
- *sorter*
- *cityList*
- *movieScrollList-large*

movies/countries
- *sorter*
- *countryList*
- *movieScrollList-large*


movies/keywords
- keywordFilter
- *sorter*
- *keywordMovieList*
  - *keywordList*
  - *movieScrollList-small*


movies/keywords/:id
- *sorter*
- *keyword*
- *movieScrollList-large*


movies/detail/:id
- thumbnail
- title


login
- logo
- oauth
- oauth2
- oauth3
*/
